use_frameworks!

platform :ios, '8.0'

target 'cocoaTest_Example' do
  pod 'cocoaTest', :path => '../'

  target 'cocoaTest_Tests' do
    inherit! :search_paths

    pod 'Kiwi'
    pod 'FBSnapshotTestCase'
  end
end
